import { createHash } from 'crypto';
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, basename } from 'path';

const iconsDir = './wwwroot/icons';
const outputFile = './Styles/components/_icons.scss';

const files = readdirSync(iconsDir)
    .filter(f => f.endsWith('.svg'))
    .sort();

const lines = [
    '// Auto-generated by hash-icons.mjs — do not edit manually. Run: npm run build:custom',
    '.icon {',
    '    display: inline-block;',
    '    background-color: currentColor;',
    '    mask-repeat: no-repeat;',
    '    mask-size: contain;',
    '    mask-position: center;',
    '    vertical-align: middle;',
    '    flex-shrink: 0;',
    '}',
    '',
];

for (const file of files) {
    const content = readFileSync(join(iconsDir, file));
    const hash = createHash('sha256').update(content).digest('hex').slice(0, 8);
    const name = basename(file, '.svg');
    const pad = ' '.repeat(Math.max(1, 28 - name.length));
    lines.push(`.icon-${name}${pad}{ mask-image: url('/icons/${file}?v=${hash}'); }`);
}

writeFileSync(outputFile, lines.join('\n') + '\n');
console.log(`hash-icons: generated _icons.scss with ${files.length} icons`);
