import { createHash } from 'crypto';
import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, basename } from 'path';

const iconsDir = './wwwroot/icons';
const outputFile = './Styles/components/_icons.scss';

const files = readdirSync(iconsDir)
    .filter(f => f.endsWith('.svg'))
    .sort();

const BASE_STYLES = [
    '    display: inline-block;',
    '    background-color: currentColor;',
    '    mask-repeat: no-repeat;',
    '    mask-size: contain;',
    '    mask-position: center;',
    '    vertical-align: middle;',
    '    flex-shrink: 0;',
];

const lines = [
    '// Auto-generated by hash-icons.mjs — do not edit manually. Run: npm run build:custom',
    '.icon {',
    ...BASE_STYLES,
    '}',
    '',
    '// sn-icon: namespaced alias with default 1rem size + size modifiers',
    '.sn-icon {',
    ...BASE_STYLES,
    '    width: 1rem;',
    '    height: 1rem;',
    '}',
    '.sn-icon--xs { width: 0.875rem; height: 0.875rem; }',
    '.sn-icon--sm { width: 1rem;     height: 1rem; }',
    '.sn-icon--md { width: 1.25rem;  height: 1.25rem; }',
    '.sn-icon--lg { width: 2rem;     height: 2rem; }',
    '.sn-icon--xl { width: 2.5rem;   height: 2.5rem; }',
    '',
];

for (const file of files) {
    const content = readFileSync(join(iconsDir, file));
    const hash = createHash('sha256').update(content).digest('hex').slice(0, 8);
    const name = basename(file, '.svg');
    const pad = ' '.repeat(Math.max(1, 28 - name.length));
    lines.push(`.icon-${name}${pad}{ mask-image: url('/icons/${file}?v=${hash}'); }`);
}

writeFileSync(outputFile, lines.join('\n') + '\n');
console.log(`hash-icons: generated _icons.scss with ${files.length} icons`);
