<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>snakk-worker-secrets</UserSecretsId>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.6.0" />
	<PackageReference Include="SixLabors.ImageSharp" Version="[3.1.12, 4.0.0)" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\Snakk.ServiceDefaults\Snakk.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\core\Snakk.Application\Snakk.Application.csproj" />
    <ProjectReference Include="..\..\core\Snakk.Infrastructure\Snakk.Infrastructure.csproj" />
    <ProjectReference Include="..\..\core\Snakk.Infrastructure.Database\Snakk.Infrastructure.Database.csproj" />
    <ProjectReference Include="..\..\core\Snakk.Domain\Snakk.Domain.csproj" />
    <ProjectReference Include="..\..\core\Snakk.Shared\Snakk.Shared.csproj" />
  </ItemGroup>

</Project>
