// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Snakk.Infrastructure.Database;

#nullable disable

namespace Snakk.Infrastructure.Database.Migrations
{
    [DbContext(typeof(SnakkDbContext))]
    [Migration("20260130002608_EnumToIntegerMigration")]
    partial class EnumToIntegerMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DiscussionCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ExposeToPlatformFeed")
                        .HasColumnType("boolean");

                    b.Property<int>("HubCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpaceCount")
                        .HasColumnType("integer");

                    b.Property<int>("VisibilityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("VisibilityId");

                    b.ToTable("Community");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.CommunityDomainDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("CommunityDomain");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.DiscussionDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReactionCount")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Discussion_IsDeleted");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug");

                    b.HasIndex("CreatedAt", "IsDeleted")
                        .IsDescending(true, false)
                        .HasDatabaseName("IX_Discussion_CreatedAt_IsDeleted_Desc");

                    b.HasIndex("LastActivityAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_Discussion_LastActivityAt_Id_Desc");

                    b.HasIndex("CreatedByUserId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Discussion_CreatedByUserId_CreatedAt_Id_Desc");

                    b.HasIndex("SpaceId", "IsPinned", "LastActivityAt", "Id")
                        .IsDescending(false, true, true, true)
                        .HasDatabaseName("IX_Discussion_SpaceId_Pinned_LastActivityAt_Id");

                    b.ToTable("Discussion");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.DiscussionReadStateDatabaseEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("DiscussionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastReadPostId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "DiscussionId");

                    b.ToTable("DiscussionReadState");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.FollowDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DiscussionId")
                        .HasColumnType("integer");

                    b.Property<int?>("FollowedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpaceId")
                        .HasColumnType("integer");

                    b.Property<int>("TargetTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("FollowedUserId");

                    b.HasIndex("LevelId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SpaceId");

                    b.HasIndex("TargetTypeId");

                    b.HasIndex("UserId", "TargetTypeId", "DiscussionId", "SpaceId", "FollowedUserId")
                        .IsUnique();

                    b.ToTable("Follow");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAnonymousReading")
                        .HasColumnType("boolean");

                    b.Property<int>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DiscussionCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequireEmailConfirmation")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpaceCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug");

                    b.ToTable("Hub");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.BanTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("BanTypeLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.CommunityVisibilityLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("CommunityVisibilityLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.FollowLevelLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FollowLevelLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.FollowTargetTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("FollowTargetTypeLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.ModerationActionLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ModerationActionLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.NotificationTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypeLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.ReactionTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ReactionTypeLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.ReportStatusLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ReportStatusLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.UserRoleLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserRoleLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.UserRoleTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserRoleTypeLookup");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.MentionDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MentionedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("PostId", "MentionedUserId")
                        .IsUnique();

                    b.ToTable("Mention");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ModerationLogDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("integer");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("HubId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("SpaceId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetDiscussionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetReportId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetUserBanId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetUserRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("HubId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SpaceId");

                    b.HasIndex("TargetDiscussionId");

                    b.HasIndex("TargetPostId");

                    b.HasIndex("TargetReportId");

                    b.HasIndex("TargetUserBanId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("TargetUserRoleId");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ModerationLog_ActorUserId_CreatedAt_Desc");

                    b.HasIndex("CommunityId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ModerationLog_CommunityId_CreatedAt_Desc");

                    b.ToTable("ModerationLog");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.NotificationDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceDiscussionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePostId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceSpaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SourceDiscussionId");

                    b.HasIndex("SourcePostId");

                    b.HasIndex("SourceSpaceId");

                    b.HasIndex("TypeId");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAt");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscussionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstPost")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReplyToPostId")
                        .HasColumnType("integer");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Post_IsDeleted");

                    b.HasIndex("ReplyToPostId")
                        .HasDatabaseName("IX_Post_ReplyToPostId");

                    b.HasIndex("CreatedAt", "DiscussionId", "IsDeleted")
                        .IsDescending(true, false, false)
                        .HasDatabaseName("IX_Post_CreatedAt_DiscussionId_IsDeleted");

                    b.HasIndex("CreatedByUserId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Post_CreatedByUserId_CreatedAt_Id_Desc");

                    b.HasIndex("DiscussionId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_Post_DiscussionId_CreatedAt_Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.PostRevisionDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EditedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("EditedByUserPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("PostPublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EditedByUserId");

                    b.HasIndex("PostId");

                    b.ToTable("PostRevision");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReactionDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId", "TypeId")
                        .IsUnique();

                    b.ToTable("Reaction");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReportCommentDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ReportId");

                    b.ToTable("ReportComment");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReportDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<int?>("HubId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReasonId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportedDiscussionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportedPostId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpaceId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("HubId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ReasonId");

                    b.HasIndex("ReportedDiscussionId");

                    b.HasIndex("ReportedPostId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("SpaceId");

                    b.HasIndex("StatusId", "CommunityId", "CreatedAt")
                        .HasDatabaseName("IX_Report_Status_CommunityId_CreatedAt");

                    b.HasIndex("StatusId", "HubId", "CreatedAt")
                        .HasDatabaseName("IX_Report_Status_HubId_CreatedAt");

                    b.HasIndex("StatusId", "SpaceId", "CreatedAt")
                        .HasDatabaseName("IX_Report_Status_SpaceId_CreatedAt");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReportReasonDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("HubId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HubId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SpaceId");

                    b.ToTable("ReportReason");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAnonymousReading")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DiscussionCount")
                        .HasColumnType("integer");

                    b.Property<int>("HubId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequireEmailConfirmation")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Slug");

                    b.ToTable("Space");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.UserBanDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BanTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BannedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HubId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int?>("SpaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnbannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UnbannedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BanTypeId");

                    b.HasIndex("BannedByUserId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("HubId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SpaceId");

                    b.HasIndex("UnbannedByUserId");

                    b.HasIndex("UserId", "UnbannedAt", "ExpiresAt")
                        .HasDatabaseName("IX_UserBan_UserId_UnbannedAt_ExpiresAt");

                    b.ToTable("UserBan");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OAuthProvider")
                        .HasColumnType("text");

                    b.Property<string>("OAuthProviderId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<bool>("PreferEndlessScroll")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("IX_User_DisplayName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_User_IsDeleted");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.UserRoleDatabaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommunityId")
                        .HasColumnType("integer");

                    b.Property<int?>("HubId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RevokedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpaceId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("CommunityId", "RoleId", "RevokedAt")
                        .HasDatabaseName("IX_UserRole_CommunityId_Role_RevokedAt");

                    b.HasIndex("HubId", "RoleId", "RevokedAt")
                        .HasDatabaseName("IX_UserRole_HubId_Role_RevokedAt");

                    b.HasIndex("SpaceId", "RoleId", "RevokedAt")
                        .HasDatabaseName("IX_UserRole_SpaceId_Role_RevokedAt");

                    b.HasIndex("UserId", "RoleId", "RevokedAt")
                        .HasDatabaseName("IX_UserRole_UserId_RoleId_RevokedAt");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.CommunityVisibilityLookup", "Visibility")
                        .WithMany("Communities")
                        .HasForeignKey("VisibilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Visibility");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.CommunityDomainDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", "Community")
                        .WithMany("Domains")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.DiscussionDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", "Space")
                        .WithMany("Discussions")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.FollowDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.DiscussionDatabaseEntity", "Discussion")
                        .WithMany()
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "FollowedUser")
                        .WithMany()
                        .HasForeignKey("FollowedUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.FollowLevelLookup", "Level")
                        .WithMany("Follows")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.FollowTargetTypeLookup", "TargetType")
                        .WithMany("Follows")
                        .HasForeignKey("TargetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discussion");

                    b.Navigation("FollowedUser");

                    b.Navigation("Level");

                    b.Navigation("Space");

                    b.Navigation("TargetType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", "Community")
                        .WithMany("Hubs")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.MentionDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "MentionedUser")
                        .WithMany()
                        .HasForeignKey("MentionedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MentionedUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ModerationLogDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.ModerationActionLookup", "Action")
                        .WithMany("ModerationLogs")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", "Hub")
                        .WithMany()
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.DiscussionDatabaseEntity", "TargetDiscussion")
                        .WithMany()
                        .HasForeignKey("TargetDiscussionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", "TargetPost")
                        .WithMany()
                        .HasForeignKey("TargetPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.ReportDatabaseEntity", "TargetReport")
                        .WithMany()
                        .HasForeignKey("TargetReportId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserBanDatabaseEntity", "TargetUserBan")
                        .WithMany()
                        .HasForeignKey("TargetUserBanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserRoleDatabaseEntity", "TargetUserRole")
                        .WithMany()
                        .HasForeignKey("TargetUserRoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Action");

                    b.Navigation("ActorUser");

                    b.Navigation("Community");

                    b.Navigation("Hub");

                    b.Navigation("Space");

                    b.Navigation("TargetDiscussion");

                    b.Navigation("TargetPost");

                    b.Navigation("TargetReport");

                    b.Navigation("TargetUser");

                    b.Navigation("TargetUserBan");

                    b.Navigation("TargetUserRole");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.NotificationDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.DiscussionDatabaseEntity", "SourceDiscussion")
                        .WithMany()
                        .HasForeignKey("SourceDiscussionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", "SourcePost")
                        .WithMany()
                        .HasForeignKey("SourcePostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", "SourceSpace")
                        .WithMany()
                        .HasForeignKey("SourceSpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.NotificationTypeLookup", "Type")
                        .WithMany("Notifications")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("RecipientUser");

                    b.Navigation("SourceDiscussion");

                    b.Navigation("SourcePost");

                    b.Navigation("SourceSpace");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.DiscussionDatabaseEntity", "Discussion")
                        .WithMany("Posts")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", "ReplyToPost")
                        .WithMany()
                        .HasForeignKey("ReplyToPostId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Discussion");

                    b.Navigation("ReplyToPost");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.PostRevisionDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "EditedByUser")
                        .WithMany()
                        .HasForeignKey("EditedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EditedByUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReactionDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.ReactionTypeLookup", "Type")
                        .WithMany("Reactions")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReportCommentDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.ReportDatabaseEntity", "Report")
                        .WithMany("Comments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReportDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", "Hub")
                        .WithMany()
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.ReportReasonDatabaseEntity", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.DiscussionDatabaseEntity", "ReportedDiscussion")
                        .WithMany()
                        .HasForeignKey("ReportedDiscussionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.PostDatabaseEntity", "ReportedPost")
                        .WithMany()
                        .HasForeignKey("ReportedPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "ReporterUser")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.ReportStatusLookup", "Status")
                        .WithMany("Reports")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("Hub");

                    b.Navigation("Reason");

                    b.Navigation("ReportedDiscussion");

                    b.Navigation("ReportedPost");

                    b.Navigation("ReportedUser");

                    b.Navigation("ReporterUser");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Space");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReportReasonDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", "Hub")
                        .WithMany()
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Community");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Hub");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", "Hub")
                        .WithMany("Spaces")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hub");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.UserBanDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.BanTypeLookup", "BanType")
                        .WithMany("UserBans")
                        .HasForeignKey("BanTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "BannedByUser")
                        .WithMany()
                        .HasForeignKey("BannedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", "Hub")
                        .WithMany()
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "UnbannedByUser")
                        .WithMany()
                        .HasForeignKey("UnbannedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BanType");

                    b.Navigation("BannedByUser");

                    b.Navigation("Community");

                    b.Navigation("Hub");

                    b.Navigation("Space");

                    b.Navigation("UnbannedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.UserRoleLookup", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.UserRoleDatabaseEntity", b =>
                {
                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", "Hub")
                        .WithMany()
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.Lookups.UserRoleTypeLookup", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Snakk.Infrastructure.Database.Entities.UserDatabaseEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Community");

                    b.Navigation("Hub");

                    b.Navigation("RevokedByUser");

                    b.Navigation("Role");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.CommunityDatabaseEntity", b =>
                {
                    b.Navigation("Domains");

                    b.Navigation("Hubs");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.DiscussionDatabaseEntity", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.HubDatabaseEntity", b =>
                {
                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.BanTypeLookup", b =>
                {
                    b.Navigation("UserBans");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.CommunityVisibilityLookup", b =>
                {
                    b.Navigation("Communities");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.FollowLevelLookup", b =>
                {
                    b.Navigation("Follows");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.FollowTargetTypeLookup", b =>
                {
                    b.Navigation("Follows");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.ModerationActionLookup", b =>
                {
                    b.Navigation("ModerationLogs");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.NotificationTypeLookup", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.ReactionTypeLookup", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.ReportStatusLookup", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.UserRoleLookup", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.Lookups.UserRoleTypeLookup", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.ReportDatabaseEntity", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Snakk.Infrastructure.Database.Entities.SpaceDatabaseEntity", b =>
                {
                    b.Navigation("Discussions");
                });
#pragma warning restore 612, 618
        }
    }
}
