// Smoke test: 1 VU, 30 seconds. Catches "everything is on fire" before
// running the heavier scenarios. Validates auth + read paths + a basic POST.
//
// Run:
//   docker compose --profile loadtest run --rm k6 run \
//     -o experimental-opentelemetry /scripts/scenarios/smoke.js

import { sleep, check, group } from 'k6';
import { TEST_USERS, DEFAULT_COMMUNITY, DEFAULT_HUB_SPACES, pickRandom, ok, tolerantThresholds } from '../lib/config.js';
import { checkOk } from '../lib/metrics.js';
import { login } from '../lib/auth.js';
import {
    getHomePage,
    getCommunityPage,
    getHubPage,
    getSpacePage,
    pickDiscussionLink,
    getDiscussionDetail,
    searchSpaces,
    loadNewDiscussionForm,
    extractFormTokens,
    createStandardDiscussion,
} from '../lib/endpoints.js';

export const options = {
    vus: 1,
    duration: '30s',
    thresholds: tolerantThresholds,
};

export default function () {
    const { hub, space } = pickRandom(DEFAULT_HUB_SPACES);

    group('public read paths', () => {
        checkOk(getHomePage(),                       'home',      '<!DOCTYPE');
        checkOk(getCommunityPage(DEFAULT_COMMUNITY), 'community', '<!DOCTYPE');
        checkOk(getHubPage(hub),                     'hub',       '<!DOCTYPE');

        const spacePage = getSpacePage(hub, space);
        checkOk(spacePage, 'space', '<!DOCTYPE');

        const link = pickDiscussionLink(spacePage.body);
        if (link) {
            checkOk(getDiscussionDetail(link), 'discussion-detail', '<!DOCTYPE');
        }
    });

    group('search', () => {
        checkOk(searchSpaces('general'), 'search-spaces');
    });

    group('authenticated write', () => {
        const loggedIn = login(TEST_USERS[0]);
        if (!loggedIn) return;

        const form = loadNewDiscussionForm();
        checkOk(form, 'new-discussion-form', '<!DOCTYPE');

        const { token, spaceId } = extractFormTokens(form.body);
        if (!token || !spaceId) {
            // Anonymous load may have skipped the form; that's OK for smoke.
            return;
        }

        const created = createStandardDiscussion(
            `k6 smoke ${Date.now()}`,
            'Generated by k6 smoke test — feel free to delete.',
            spaceId,
            token,
        );
        check(created, {
            'create-discussion is 302 (redirect to new post)': r => r.status === 302,
        });
    });

    sleep(1);
}
