// Authenticated write scenario. Each VU logs in once in setup, then in the
// main loop creates a new standard discussion at moderate cadence. Tests the
// write path: antiforgery validation, gRPC call to PostService.CreatePost,
// Postgres INSERT chain, outbox event emission.
//
// Run:
//   docker compose --profile loadtest run --rm k6 run \
//     -e VUS=10 -e DURATION=2m \
//     -o experimental-opentelemetry /scripts/scenarios/write.js
//
// NOTE: each iteration creates a real discussion in the seeded DB. To clean
// up after a soak test, look for titles starting with "k6 write" in the
// Snakk admin UI, or truncate the test database between runs.

import { sleep, check, group } from 'k6';
import { TEST_USERS, pickRandom, tolerantThresholds } from '../lib/config.js';
import { checkOk } from '../lib/metrics.js';
import { login } from '../lib/auth.js';
import {
    loadNewDiscussionForm,
    extractFormTokens,
    createStandardDiscussion,
    getNotifications,
    getUnreadCount,
} from '../lib/endpoints.js';

export const options = {
    stages: [
        { duration: '15s', target: parseInt(__ENV.VUS || '10') },
        { duration: __ENV.DURATION || '2m', target: parseInt(__ENV.VUS || '10') },
        { duration: '15s', target: 0 },
    ],
    thresholds: {
        ...tolerantThresholds,
        'http_req_duration{name:create-discussion}':   ['p(95)<3000'],
        'http_req_duration{name:new-discussion-form}': ['p(95)<1500'],
    },
};

const SAMPLE_BODIES = [
    'Generated by k6 load test. This is meant to exercise the write path.',
    'Hello world. Testing post creation under load.',
    'A longer body with multiple sentences. Markdown is _not_ rendered here, just stored. The content service should handle this size without trouble. Adding a few more characters to reach a few hundred bytes which is more representative of real posts.',
    'Short one.',
];

export function setup() {
    // Pre-discover a valid SpaceId by hitting the new-discussion form once
    // anonymously (the form is auth-gated so we need to login first). We do
    // this in setup so the VU loop doesn't pay this cost.
    return { /* nothing reusable yet — login state is per-VU below */ };
}

export default function () {
    // Pick a user; each VU rotates so we exercise multiple identities.
    const user = pickRandom(TEST_USERS);

    group('login', () => {
        const ok = login(user);
        if (!ok) return;
    });

    group('read notifications', () => {
        checkOk(getUnreadCount(),   'unread-count');
        checkOk(getNotifications(), 'notifications');
    });

    let spaceId = null;
    let token = null;
    group('load form', () => {
        const form = loadNewDiscussionForm();
        const okForm = checkOk(form, 'new-discussion-form', '<!DOCTYPE');
        if (!okForm) return;
        const t = extractFormTokens(form.body);
        spaceId = t.spaceId;
        token = t.token;
    });

    if (spaceId && token) {
        group('create discussion', () => {
            const created = createStandardDiscussion(
                `k6 write ${user.name} ${Date.now()}`,
                pickRandom(SAMPLE_BODIES),
                spaceId,
                token,
            );
            check(created, { 'create is 302': r => r.status === 302 });
        });
    }

    sleep(Math.random() * 3 + 2);
}
