<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.1.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\services\Snakk.Api\Snakk.Api.csproj" />
    <ProjectReference Include="..\..\services\Snakk.Gateway\Snakk.Gateway.csproj" />
    <ProjectReference Include="..\..\services\Snakk.Realtime\Snakk.Realtime.csproj" />
    <ProjectReference Include="..\..\services\Snakk.Worker\Snakk.Worker.csproj" />
    <ProjectReference Include="..\..\apps\Snakk.Setup\Snakk.Setup.csproj" />
    <ProjectReference Include="..\..\apps\Snakk.Web\Snakk.Web.csproj" />
    <ProjectReference Include="..\..\apps\Snakk.Auth\Snakk.Auth.csproj" />
    <ProjectReference Include="..\..\apps\Snakk.AdminWeb\Snakk.AdminWeb.csproj" />
  </ItemGroup>

</Project>
