<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release</Configurations>
    <StaticWebAssetsEnabled>true</StaticWebAssetsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <!-- Fluent UI Blazor -->
    <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />

    <!-- JWT Authentication -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="MudBlazor" Version="9.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.3" />

    <!-- gRPC -->
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aspire\Snakk.ServiceDefaults\Snakk.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\core\Snakk.Protos\Snakk.Protos.csproj" />
    <ProjectReference Include="..\..\core\Snakk.Application\Snakk.Application.csproj" />
  </ItemGroup>

</Project>
