// Auto-generates Helpers/T.g.cs from en.json and validates that every other
// *.json under Locales/ has the exact same key set. Missing/extra keys cause
// a non-zero exit (so MSBuild fails the build).

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';

const localesDir = './Locales';
const canonicalFile = 'en.json';
const outputFile = './Helpers/T.g.cs';

function flatten(obj, prefix = '') {
    const out = {};
    for (const [k, v] of Object.entries(obj)) {
        const key = prefix ? `${prefix}.${k}` : k;
        if (v && typeof v === 'object' && !Array.isArray(v)) {
            Object.assign(out, flatten(v, key));
        } else {
            out[key] = v;
        }
    }
    return out;
}

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

const escapeXml = (s) => String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// ─── Load canonical (en) ──────────────────────────────────────────────────
const canonical = JSON.parse(readFileSync(join(localesDir, canonicalFile), 'utf8'));
const canonicalFlat = flatten(canonical);
const canonicalKeys = new Set(Object.keys(canonicalFlat));

// ─── Validate other locales ──────────────────────────────────────────────
const otherFiles = readdirSync(localesDir)
    .filter(f => f.endsWith('.json') && f !== canonicalFile)
    .sort();

let hasError = false;
for (const f of otherFiles) {
    const data = flatten(JSON.parse(readFileSync(join(localesDir, f), 'utf8')));
    const keys = new Set(Object.keys(data));
    const missing = [...canonicalKeys].filter(k => !keys.has(k));
    const extra = [...keys].filter(k => !canonicalKeys.has(k));
    if (missing.length || extra.length) {
        hasError = true;
        console.error(`\n[locale] ${f}:`);
        for (const k of missing) console.error(`  MISSING: ${k}`);
        for (const k of extra)   console.error(`  EXTRA:   ${k}`);
    }
}
if (hasError) {
    console.error('\nLocale validation failed. Fix key mismatches against en.json.');
    process.exit(1);
}

// ─── Emit C# class tree mirroring the JSON structure ──────────────────────
function emit(node, path, indent) {
    const pad = '    '.repeat(indent);
    const leaves = [];
    const nested = [];
    for (const [k, v] of Object.entries(node)) {
        if (v && typeof v === 'object' && !Array.isArray(v)) nested.push([k, v]);
        else leaves.push([k, v]);
    }
    leaves.sort(([a], [b]) => a.localeCompare(b));
    nested.sort(([a], [b]) => a.localeCompare(b));

    const lines = [];
    for (const [k, v] of leaves) {
        const fullKey = [...path, k].join('.');
        lines.push(`${pad}/// <summary>${escapeXml(v)}</summary>`);
        lines.push(`${pad}public static string ${pascal(k)} => _loc["${fullKey}"];`);
    }
    for (const [k, v] of nested) {
        if (lines.length) lines.push('');
        lines.push(`${pad}public static class ${pascal(k)}`);
        lines.push(`${pad}{`);
        lines.push(emit(v, [...path, k], indent + 1));
        lines.push(`${pad}}`);
    }
    return lines.join('\n');
}

const body = emit(canonical, [], 1);

const output = [
    '// <auto-generated>',
    '// Generated by Locales/gen-strings.mjs from en.json. Do not edit manually.',
    '// </auto-generated>',
    '',
    '#nullable enable',
    'namespace Snakk.Web.Helpers;',
    '',
    'using System.Collections.Generic;',
    '',
    'public static class T',
    '{',
    '    internal static IReadOnlyDictionary<string, string> _loc =',
    '        new Dictionary<string, string>(System.StringComparer.Ordinal);',
    '',
    body,
    '}',
    ''
].join('\n');

writeFileSync(outputFile, output);
console.log(`gen-strings: generated T.g.cs (${Object.keys(canonicalFlat).length} keys, ${otherFiles.length + 1} locales)`);
