// Auto-generates Scripts/locales/t.g.ts from the locale selected via
// SNAKK_LOCALE (default "en"). Emits a frozen nested object literal so
// TypeScript can infer literal string types automatically.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';

const localesDir = './Locales';
const outputFile = './Scripts/locales/t.g.ts';
const requested = process.env.SNAKK_LOCALE || 'en';

const canonicalPath = join(localesDir, 'en.json');
const requestedPath = join(localesDir, `${requested}.json`);

let activeLocale = requested;
let sourcePath = requestedPath;
if (!existsSync(requestedPath)) {
    console.warn(`gen-ts: locale "${requested}" not found, falling back to en.json`);
    activeLocale = 'en';
    sourcePath = canonicalPath;
}

const data = JSON.parse(readFileSync(sourcePath, 'utf8'));

function emit(node, indent) {
    const pad = '    '.repeat(indent);
    const inner = '    '.repeat(indent + 1);
    const entries = Object.entries(node).sort(([a], [b]) => a.localeCompare(b));
    const lines = ['{'];
    entries.forEach(([k, v], i) => {
        const comma = i === entries.length - 1 ? '' : ',';
        const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
        if (v && typeof v === 'object' && !Array.isArray(v)) {
            lines.push(`${inner}${key}: ${emit(v, indent + 1)}${comma}`);
        } else {
            lines.push(`${inner}${key}: ${JSON.stringify(v)}${comma}`);
        }
    });
    lines.push(`${pad}}`);
    return lines.join('\n');
}

const body = emit(data, 0);

const output = [
    '// <auto-generated>',
    `// Generated by Locales/gen-ts.mjs from ${activeLocale}.json. Do not edit manually.`,
    '// </auto-generated>',
    '',
    `export const T = Object.freeze(${body} as const);`,
    ''
].join('\n');

const outDir = dirname(outputFile);
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
writeFileSync(outputFile, output);
console.log(`gen-ts: generated t.g.ts (locale=${activeLocale})`);
