<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.3" />
    <PackageReference Include="TUnit" Version="1.19.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\apps\Snakk.Web\Snakk.Web.csproj" />
    <ProjectReference Include="..\..\apps\Snakk.Admin\Snakk.Admin.csproj">
      <Aliases>Admin</Aliases>
    </ProjectReference>
  </ItemGroup>

</Project>
